### ISSUE TITLE
Проброска окружения фронта

### ISSUE THREAD

**Issue by PrudyvusP** [web-search-for-the-nearest-hospitals/backend#121]
Общими усилиями было установлено, что проблемы деплоя сборки фронта оказались связаны с проброской окружения фронта. В текущих реалиях перед выполнением команды `RUN npm run build` необходимо подсунуть файл `.env` для корректной сборки.
Необходимо реализовать тем или иным способом проброс из secretes гитхаба (ключ API карт) в сборку)

**Comment by PrudyvusP** [comment]
```docker
FROM node:lts-bookworm-slim as build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN --mount=type=secret,id=VITE_NODE_ENV \
    --mount=type=secret,id=VITE_YAMAP_API_KEY \
    --mount=type=secret,id=VITE_BACK_URL \
    echo "VITE_NODE_ENV=$(cat /run/secrets/VITE_NODE_ENV)" > .env && \
    echo "VITE_YAMAP_API_KEY=$(cat /run/secrets/VITE_YAMAP_API_KEY)" >> .env && \
    echo "VITE_BACK_URL=$(cat /run/secrets/VITE_BACK_URL)" >> .env
RUN npm run build
```

```yaml
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            secrets: |
              "VITE_YAMAP_API_KEY=${{ secrets.VITE_YAMAP_API_KEY }}"
              "VITE_BACK_URL=${{ secrets.VITE_BACK_URL }}"
              "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}"
```
